// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

namespace Steamworks {
	/// <summary>
	/// Inform invokers use <see cref="CallResult{T}"/> to receive async result.
	/// </summary>
	[System.AttributeUsage(System.AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public sealed class SteamHasAsyncCallResultAttribute : System.Attribute {
		private System.Type callbackType; // for vs project ignore suggestion IDE0044, I'm not sure if Unity supports readonly field

		// See the attribute guidelines at 
		//  http://go.microsoft.com/fwlink/?LinkId=85236

		internal SteamHasAsyncCallResultAttribute(System.Type callbackType) {
			this.callbackType = callbackType;
		}
		
		/// <summary>
		/// Result type of the async operation.
		/// </summary>
		public System.Type CallbackType { get { return callbackType; } }
    }

	/// <summary>
	/// Inform invokers use <see cref="Callback{T}"/> to receive async result.
	/// </summary>
	[System.AttributeUsage(System.AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public sealed class SteamHasAsyncCallbackAttribute : System.Attribute {
		private System.Type callbackType; // for vs project ignore suggestion IDE0044, I'm not sure if Unity supports readonly field

		// See the attribute guidelines at 
		//  http://go.microsoft.com/fwlink/?LinkId=85236

		internal SteamHasAsyncCallbackAttribute(System.Type callbackType) {
			this.callbackType = callbackType;
		}

		/// <summary>
		/// Result type of the async operation.
		/// </summary>
		public System.Type CallbackType { get { return callbackType; } }
    }
}

#endif // !DISABLESTEAMWORKS
