// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

namespace Steamworks {
	public static class Version {
		public const string SteamworksNETVersion = "2024.8.0";
		public const string SteamworksSDKVersion = "1.60";
		public const string SteamAPIDLLVersion = "08.97.99.70";
		public const int SteamAPIDLLSize = 265064;
		public const int SteamAPI64DLLSize = 300392;
	}
}

#endif // !DISABLESTEAMWORKS
