#!/usr/bin/env bash

GAMENAME="REPLACEWITHYOURGAMENAME"
ARCH=`uname -m`

if [ "$ARCH" != "x86_64" ]; then
	ARCH="x86"
fi

export LD_LIBRARY_PATH="./"$GAMENAME"_Data/Plugins/"$ARCH"/:$LD_LIBRARY_PATH"

exec "./"$GAMENAME"."$ARCH "$@"
