// This file is automatically generated!

using System;
using System.Runtime.InteropServices;

namespace Steamworks {
	public static class SteamHTTP {
		public static uint CreateHTTPRequest(EHTTPMethod eHTTPRequestMethod, string pchAbsoluteURL) {
			return NativeMethods.ISteamHTTP_CreateHTTPRequest(eHTTPRequestMethod, new InteropHelp.UTF8String(pchAbsoluteURL));
		}

		public static bool SetHTTPRequestContextValue(uint hRequest, ulong ulContextValue) {
			return NativeMethods.ISteamHTTP_SetHTTPRequestContextValue(hRequest, ulContextValue);
		}

		public static bool SetHTTPRequestNetworkActivityTimeout(uint hRequest, uint unTimeoutSeconds) {
			return NativeMethods.ISteamHTTP_SetHTTPRequestNetworkActivityTimeout(hRequest, unTimeoutSeconds);
		}

		public static bool SetHTTPRequestHeaderValue(uint hRequest, string pchHeaderName, string pchHeaderValue) {
			return NativeMethods.ISteamHTTP_SetHTTPRequestHeaderValue(hRequest, new InteropHelp.UTF8String(pchHeaderName), new InteropHelp.UTF8String(pchHeaderValue));
		}

		public static bool SetHTTPRequestGetOrPostParameter(uint hRequest, string pchParamName, string pchParamValue) {
			return NativeMethods.ISteamHTTP_SetHTTPRequestGetOrPostParameter(hRequest, new InteropHelp.UTF8String(pchParamName), new InteropHelp.UTF8String(pchParamValue));
		}

		public static bool SendHTTPRequest(uint hRequest, ref ulong pCallHandle) {
			return NativeMethods.ISteamHTTP_SendHTTPRequest(hRequest, ref pCallHandle);
		}

		public static bool SendHTTPRequestAndStreamResponse(uint hRequest, ref ulong pCallHandle) {
			return NativeMethods.ISteamHTTP_SendHTTPRequestAndStreamResponse(hRequest, ref pCallHandle);
		}

		public static bool DeferHTTPRequest(uint hRequest) {
			return NativeMethods.ISteamHTTP_DeferHTTPRequest(hRequest);
		}

		public static bool PrioritizeHTTPRequest(uint hRequest) {
			return NativeMethods.ISteamHTTP_PrioritizeHTTPRequest(hRequest);
		}

		public static bool GetHTTPResponseHeaderSize(uint hRequest, string pchHeaderName, out uint unResponseHeaderSize) {
			return NativeMethods.ISteamHTTP_GetHTTPResponseHeaderSize(hRequest, new InteropHelp.UTF8String(pchHeaderName), out unResponseHeaderSize);
		}

		public static bool GetHTTPResponseHeaderValue(uint hRequest, string pchHeaderName, ref byte pHeaderValueBuffer, uint unBufferSize) {
			return NativeMethods.ISteamHTTP_GetHTTPResponseHeaderValue(hRequest, new InteropHelp.UTF8String(pchHeaderName), ref pHeaderValueBuffer, unBufferSize);
		}

		public static bool GetHTTPResponseBodySize(uint hRequest, out uint unBodySize) {
			return NativeMethods.ISteamHTTP_GetHTTPResponseBodySize(hRequest, out unBodySize);
		}

		public static bool GetHTTPResponseBodyData(uint hRequest, ref byte pBodyDataBuffer, uint unBufferSize) {
			return NativeMethods.ISteamHTTP_GetHTTPResponseBodyData(hRequest, ref pBodyDataBuffer, unBufferSize);
		}

		public static bool GetHTTPStreamingResponseBodyData(uint hRequest, uint cOffset, ref byte pBodyDataBuffer, uint unBufferSize) {
			return NativeMethods.ISteamHTTP_GetHTTPStreamingResponseBodyData(hRequest, cOffset, ref pBodyDataBuffer, unBufferSize);
		}

		public static bool ReleaseHTTPRequest(uint hRequest) {
			return NativeMethods.ISteamHTTP_ReleaseHTTPRequest(hRequest);
		}

		public static bool GetHTTPDownloadProgressPct(uint hRequest, out float pflPercentOut) {
			return NativeMethods.ISteamHTTP_GetHTTPDownloadProgressPct(hRequest, out pflPercentOut);
		}

		public static bool SetHTTPRequestRawPostBody(uint hRequest, string pchContentType, ref byte pubBody, uint unBodyLen) {
			return NativeMethods.ISteamHTTP_SetHTTPRequestRawPostBody(hRequest, new InteropHelp.UTF8String(pchContentType), ref pubBody, unBodyLen);
		}
	}
}