// This file is automatically generated!

using System;
using System.Runtime.InteropServices;

namespace Steamworks {
	public static class SteamGameServerStats {
		public static SteamAPICall_t RequestUserStats(ulong steamIDUser) {
			return NativeMethods.ISteamGameServerStats_RequestUserStats(steamIDUser);
		}

		public static bool GetUserStat(ulong steamIDUser, string pchName, out int pData) {
			return NativeMethods.ISteamGameServerStats_GetUserStat(steamIDUser, new InteropHelp.UTF8String(pchName), out pData);
		}

		public static bool GetUserStat(ulong steamIDUser, string pchName, out float pData) {
			return NativeMethods.ISteamGameServerStats_GetUserStat_(steamIDUser, new InteropHelp.UTF8String(pchName), out pData);
		}

		public static bool GetUserAchievement(ulong steamIDUser, string pchName, out bool pbAchieved) {
			return NativeMethods.ISteamGameServerStats_GetUserAchievement(steamIDUser, new InteropHelp.UTF8String(pchName), out pbAchieved);
		}

		public static bool SetUserStat(ulong steamIDUser, string pchName, int nData) {
			return NativeMethods.ISteamGameServerStats_SetUserStat(steamIDUser, new InteropHelp.UTF8String(pchName), nData);
		}

		public static bool SetUserStat(ulong steamIDUser, string pchName, float fData) {
			return NativeMethods.ISteamGameServerStats_SetUserStat_(steamIDUser, new InteropHelp.UTF8String(pchName), fData);
		}

		public static bool UpdateUserAvgRateStat(ulong steamIDUser, string pchName, float flCountThisSession, double dSessionLength) {
			return NativeMethods.ISteamGameServerStats_UpdateUserAvgRateStat(steamIDUser, new InteropHelp.UTF8String(pchName), flCountThisSession, dSessionLength);
		}

		public static bool SetUserAchievement(ulong steamIDUser, string pchName) {
			return NativeMethods.ISteamGameServerStats_SetUserAchievement(steamIDUser, new InteropHelp.UTF8String(pchName));
		}

		public static bool ClearUserAchievement(ulong steamIDUser, string pchName) {
			return NativeMethods.ISteamGameServerStats_ClearUserAchievement(steamIDUser, new InteropHelp.UTF8String(pchName));
		}

		public static SteamAPICall_t StoreUserStats(ulong steamIDUser) {
			return NativeMethods.ISteamGameServerStats_StoreUserStats(steamIDUser);
		}
	}
}