/// <auto-generated/>
// This file is generated by CodeGen/src/struct.py

#if !STEAMWORKS_ANYCPU
#error This file for Any CPU variant, not meaningful to any other platform.
#endif

using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Steamworks {
	internal static partial class ConditionalMarshallerTable {
		static ConditionalMarshallerTable() {
			Dictionary<Type, Func<IntPtr, object>> marshallers = new();

