// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2018 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if UNITY_ANDROID || UNITY_IOS || UNITY_TIZEN || UNITY_TVOS || UNITY_WEBGL || UNITY_WSA || UNITY_PS4 || UNITY_WII || UNITY_XBOXONE || UNITY_SWITCH
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System;
using System.Runtime.InteropServices;
using IntPtr = System.IntPtr;

namespace Steamworks
{
    public struct SteamNetworkingIdentity
    {
        [StructLayout(LayoutKind.Explicit, Pack = 1, Size = 128)]
        public struct Data
        {
            [FieldOffset(0)]
            public UInt64 m_steamID64;

            //[FieldOffset(0)]
            //public char m_szGenericString[k_cchMaxGenericString];

            //[FieldOffset(0)]
            //public char m_szXboxPairwiseID[k_cchMaxXboxPairwiseID];

            //[FieldOffset(0)]
            //public uint8 m_genericBytes[k_cbMaxGenericBytes];

            [FieldOffset(0)]
            public SteamNetworkingIPAddr m_ip;
        }

        public ESteamNetworkingIdentityType m_eType;
        public int m_cbSize;
        public Data m_data;
    }
}

#endif //!DISABLESTEAMWORKS