// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
using IntPtr = System.IntPtr;

/// <auto-generated/>
// This file is generated by CodeGen/src/struct.py

#if !STEAMWORKS_ANYCPU
#error This file for Any CPU variant, not meaningful to any other platform.
#endif

using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Steamworks {
	internal static partial class ConditionalMarshallerTable {
		private static partial class Impl<T> {
			static Impl() {
			

			if (typeof(T) == typeof(FileDetailsResult_t) && Packsize.IsLargePack)
				Impl<FileDetailsResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<FileDetailsResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(GSReputation_t) && Packsize.IsLargePack)
				Impl<GSReputation_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<GSReputation_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(GSStatsReceived_t) && Packsize.IsLargePack)
				Impl<GSStatsReceived_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<GSStatsReceived_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(GSStatsStored_t) && Packsize.IsLargePack)
				Impl<GSStatsStored_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<GSStatsStored_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_NeedsPaint_t) && Packsize.IsLargePack)
				Impl<HTML_NeedsPaint_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_NeedsPaint_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_StartRequest_t) && Packsize.IsLargePack)
				Impl<HTML_StartRequest_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_StartRequest_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_URLChanged_t) && Packsize.IsLargePack)
				Impl<HTML_URLChanged_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_URLChanged_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_FinishedRequest_t) && Packsize.IsLargePack)
				Impl<HTML_FinishedRequest_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_FinishedRequest_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_OpenLinkInNewTab_t) && Packsize.IsLargePack)
				Impl<HTML_OpenLinkInNewTab_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_OpenLinkInNewTab_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_ChangedTitle_t) && Packsize.IsLargePack)
				Impl<HTML_ChangedTitle_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_ChangedTitle_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_LinkAtPosition_t) && Packsize.IsLargePack)
				Impl<HTML_LinkAtPosition_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_LinkAtPosition_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_JSAlert_t) && Packsize.IsLargePack)
				Impl<HTML_JSAlert_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_JSAlert_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_JSConfirm_t) && Packsize.IsLargePack)
				Impl<HTML_JSConfirm_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_JSConfirm_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_FileOpenDialog_t) && Packsize.IsLargePack)
				Impl<HTML_FileOpenDialog_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_FileOpenDialog_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_NewWindow_t) && Packsize.IsLargePack)
				Impl<HTML_NewWindow_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_NewWindow_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_StatusText_t) && Packsize.IsLargePack)
				Impl<HTML_StatusText_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_StatusText_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_ShowToolTip_t) && Packsize.IsLargePack)
				Impl<HTML_ShowToolTip_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_ShowToolTip_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTML_UpdateToolTip_t) && Packsize.IsLargePack)
				Impl<HTML_UpdateToolTip_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_UpdateToolTip_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTTPRequestCompleted_t) && Packsize.IsLargePack)
				Impl<HTTPRequestCompleted_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTTPRequestCompleted_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTTPRequestHeadersReceived_t) && Packsize.IsLargePack)
				Impl<HTTPRequestHeadersReceived_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTTPRequestHeadersReceived_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(HTTPRequestDataReceived_t) && Packsize.IsLargePack)
				Impl<HTTPRequestDataReceived_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<HTTPRequestDataReceived_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamInputConfigurationLoaded_t) && Packsize.IsLargePack)
				Impl<SteamInputConfigurationLoaded_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamInputConfigurationLoaded_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamInputGamepadSlotChange_t) && Packsize.IsLargePack)
				Impl<SteamInputGamepadSlotChange_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamInputGamepadSlotChange_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamInventoryEligiblePromoItemDefIDs_t) && Packsize.IsLargePack)
				Impl<SteamInventoryEligiblePromoItemDefIDs_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamInventoryEligiblePromoItemDefIDs_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamInventoryStartPurchaseResult_t) && Packsize.IsLargePack)
				Impl<SteamInventoryStartPurchaseResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamInventoryStartPurchaseResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamPartyBeaconLocation_t) && Packsize.IsLargePack)
				Impl<SteamPartyBeaconLocation_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamPartyBeaconLocation_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(LobbyCreated_t) && Packsize.IsLargePack)
				Impl<LobbyCreated_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<LobbyCreated_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SearchForGameProgressCallback_t) && Packsize.IsLargePack)
				Impl<SearchForGameProgressCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SearchForGameProgressCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SearchForGameResultCallback_t) && Packsize.IsLargePack)
				Impl<SearchForGameResultCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SearchForGameResultCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(RequestPlayersForGameProgressCallback_t) && Packsize.IsLargePack)
				Impl<RequestPlayersForGameProgressCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<RequestPlayersForGameProgressCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(RequestPlayersForGameResultCallback_t) && Packsize.IsLargePack)
				Impl<RequestPlayersForGameResultCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<RequestPlayersForGameResultCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(RequestPlayersForGameFinalResultCallback_t) && Packsize.IsLargePack)
				Impl<RequestPlayersForGameFinalResultCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<RequestPlayersForGameFinalResultCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SubmitPlayerResultResultCallback_t) && Packsize.IsLargePack)
				Impl<SubmitPlayerResultResultCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SubmitPlayerResultResultCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(EndGameResultCallback_t) && Packsize.IsLargePack)
				Impl<EndGameResultCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<EndGameResultCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(JoinPartyCallback_t) && Packsize.IsLargePack)
				Impl<JoinPartyCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<JoinPartyCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(CreateBeaconCallback_t) && Packsize.IsLargePack)
				Impl<CreateBeaconCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<CreateBeaconCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamNetConnectionStatusChangedCallback_t) && Packsize.IsLargePack)
				Impl<SteamNetConnectionStatusChangedCallback_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamNetConnectionStatusChangedCallback_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamTimelineGamePhaseRecordingExists_t) && Packsize.IsLargePack)
				Impl<SteamTimelineGamePhaseRecordingExists_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamTimelineGamePhaseRecordingExists_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamUGCDetails_t) && Packsize.IsLargePack)
				Impl<SteamUGCDetails_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamUGCDetails_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(CreateItemResult_t) && Packsize.IsLargePack)
				Impl<CreateItemResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<CreateItemResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(ItemInstalled_t) && Packsize.IsLargePack)
				Impl<ItemInstalled_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<ItemInstalled_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(DownloadItemResult_t) && Packsize.IsLargePack)
				Impl<DownloadItemResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<DownloadItemResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(AddUGCDependencyResult_t) && Packsize.IsLargePack)
				Impl<AddUGCDependencyResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<AddUGCDependencyResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(RemoveUGCDependencyResult_t) && Packsize.IsLargePack)
				Impl<RemoveUGCDependencyResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<RemoveUGCDependencyResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(AddAppDependencyResult_t) && Packsize.IsLargePack)
				Impl<AddAppDependencyResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<AddAppDependencyResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(RemoveAppDependencyResult_t) && Packsize.IsLargePack)
				Impl<RemoveAppDependencyResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<RemoveAppDependencyResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(GetAppDependenciesResult_t) && Packsize.IsLargePack)
				Impl<GetAppDependenciesResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<GetAppDependenciesResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(DeleteItemResult_t) && Packsize.IsLargePack)
				Impl<DeleteItemResult_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<DeleteItemResult_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(ValidateAuthTicketResponse_t) && Packsize.IsLargePack)
				Impl<ValidateAuthTicketResponse_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<ValidateAuthTicketResponse_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(MicroTxnAuthorizationResponse_t) && Packsize.IsLargePack)
				Impl<MicroTxnAuthorizationResponse_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<MicroTxnAuthorizationResponse_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(LeaderboardEntry_t) && Packsize.IsLargePack)
				Impl<LeaderboardEntry_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<LeaderboardEntry_t_LargePack>(unmanaged);
			
			if (typeof(T) == typeof(SteamNetConnectionInfo_t) && Packsize.IsLargePack)
				Impl<SteamNetConnectionInfo_t>.Marshaller = (unmanaged) =>
					System.Runtime.InteropServices.Marshal.PtrToStructure<SteamNetConnectionInfo_t_LargePack>(unmanaged);
			
			}
		}
	}
}
#endif // !DISABLESTEAMWORKS
