// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
using IntPtr = System.IntPtr;

/// <auto-generated/>
// This file is generated by CodeGen/src/struct.py

#if !STEAMWORKS_ANYCPU
#error This file for Any CPU variant, not meaningful to any other platform.
#endif

using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Steamworks {
	public static partial class SteamMarshallerTable {
		private static partial class Impl<T> {
			static Impl() {
				if (typeof(T) == typeof(FileDetailsResult_t) && Packsize.IsLargePack)
					Impl<FileDetailsResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<FileDetailsResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(FriendsGetFollowerCount_t) && Packsize.IsLargePack)
					Impl<FriendsGetFollowerCount_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<FriendsGetFollowerCount_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(FriendsIsFollowing_t) && Packsize.IsLargePack)
					Impl<FriendsIsFollowing_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<FriendsIsFollowing_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(FriendsEnumerateFollowingList_t) && Packsize.IsLargePack)
					Impl<FriendsEnumerateFollowingList_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<FriendsEnumerateFollowingList_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(EquippedProfileItems_t) && Packsize.IsLargePack)
					Impl<EquippedProfileItems_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<EquippedProfileItems_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(GSReputation_t) && Packsize.IsLargePack)
					Impl<GSReputation_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<GSReputation_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(GSStatsReceived_t) && Packsize.IsLargePack)
					Impl<GSStatsReceived_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<GSStatsReceived_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(GSStatsStored_t) && Packsize.IsLargePack)
					Impl<GSStatsStored_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<GSStatsStored_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_NeedsPaint_t) && Packsize.IsLargePack)
					Impl<HTML_NeedsPaint_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_NeedsPaint_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_StartRequest_t) && Packsize.IsLargePack)
					Impl<HTML_StartRequest_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_StartRequest_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_URLChanged_t) && Packsize.IsLargePack)
					Impl<HTML_URLChanged_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_URLChanged_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_FinishedRequest_t) && Packsize.IsLargePack)
					Impl<HTML_FinishedRequest_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_FinishedRequest_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_OpenLinkInNewTab_t) && Packsize.IsLargePack)
					Impl<HTML_OpenLinkInNewTab_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_OpenLinkInNewTab_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_ChangedTitle_t) && Packsize.IsLargePack)
					Impl<HTML_ChangedTitle_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_ChangedTitle_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_LinkAtPosition_t) && Packsize.IsLargePack)
					Impl<HTML_LinkAtPosition_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_LinkAtPosition_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_JSAlert_t) && Packsize.IsLargePack)
					Impl<HTML_JSAlert_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_JSAlert_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_JSConfirm_t) && Packsize.IsLargePack)
					Impl<HTML_JSConfirm_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_JSConfirm_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_FileOpenDialog_t) && Packsize.IsLargePack)
					Impl<HTML_FileOpenDialog_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_FileOpenDialog_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_NewWindow_t) && Packsize.IsLargePack)
					Impl<HTML_NewWindow_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_NewWindow_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_StatusText_t) && Packsize.IsLargePack)
					Impl<HTML_StatusText_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_StatusText_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_ShowToolTip_t) && Packsize.IsLargePack)
					Impl<HTML_ShowToolTip_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_ShowToolTip_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTML_UpdateToolTip_t) && Packsize.IsLargePack)
					Impl<HTML_UpdateToolTip_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTML_UpdateToolTip_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTTPRequestCompleted_t) && Packsize.IsLargePack)
					Impl<HTTPRequestCompleted_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTTPRequestCompleted_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTTPRequestHeadersReceived_t) && Packsize.IsLargePack)
					Impl<HTTPRequestHeadersReceived_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTTPRequestHeadersReceived_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(HTTPRequestDataReceived_t) && Packsize.IsLargePack)
					Impl<HTTPRequestDataReceived_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<HTTPRequestDataReceived_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(SteamInputConfigurationLoaded_t) && Packsize.IsLargePack)
					Impl<SteamInputConfigurationLoaded_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<SteamInputConfigurationLoaded_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(SteamInputGamepadSlotChange_t) && Packsize.IsLargePack)
					Impl<SteamInputGamepadSlotChange_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<SteamInputGamepadSlotChange_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(SteamInventoryEligiblePromoItemDefIDs_t) && Packsize.IsLargePack)
					Impl<SteamInventoryEligiblePromoItemDefIDs_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<SteamInventoryEligiblePromoItemDefIDs_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(SteamInventoryStartPurchaseResult_t) && Packsize.IsLargePack)
					Impl<SteamInventoryStartPurchaseResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<SteamInventoryStartPurchaseResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(SteamPartyBeaconLocation_t) && Packsize.IsLargePack)
					Impl<SteamPartyBeaconLocation_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<SteamPartyBeaconLocation_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(LobbyCreated_t) && Packsize.IsLargePack)
					Impl<LobbyCreated_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<LobbyCreated_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(JoinPartyCallback_t) && Packsize.IsLargePack)
					Impl<JoinPartyCallback_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<JoinPartyCallback_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(CreateBeaconCallback_t) && Packsize.IsLargePack)
					Impl<CreateBeaconCallback_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<CreateBeaconCallback_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(SteamNetConnectionStatusChangedCallback_t) && Packsize.IsLargePack)
					Impl<SteamNetConnectionStatusChangedCallback_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<SteamNetConnectionStatusChangedCallback_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageFileShareResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageFileShareResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageFileShareResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStoragePublishFileResult_t) && Packsize.IsLargePack)
					Impl<RemoteStoragePublishFileResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStoragePublishFileResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageDeletePublishedFileResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageDeletePublishedFileResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageDeletePublishedFileResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageEnumerateUserPublishedFilesResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageEnumerateUserPublishedFilesResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageEnumerateUserPublishedFilesResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageSubscribePublishedFileResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageSubscribePublishedFileResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageSubscribePublishedFileResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageEnumerateUserSubscribedFilesResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageEnumerateUserSubscribedFilesResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageEnumerateUserSubscribedFilesResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageUnsubscribePublishedFileResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageUnsubscribePublishedFileResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageUnsubscribePublishedFileResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageUpdatePublishedFileResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageUpdatePublishedFileResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageUpdatePublishedFileResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageDownloadUGCResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageDownloadUGCResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageDownloadUGCResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageGetPublishedFileDetailsResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageGetPublishedFileDetailsResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageGetPublishedFileDetailsResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageEnumerateWorkshopFilesResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageEnumerateWorkshopFilesResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageEnumerateWorkshopFilesResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageGetPublishedItemVoteDetailsResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageGetPublishedItemVoteDetailsResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageGetPublishedItemVoteDetailsResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageUpdateUserPublishedItemVoteResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageUpdateUserPublishedItemVoteResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageUpdateUserPublishedItemVoteResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageUserVoteDetails_t) && Packsize.IsLargePack)
					Impl<RemoteStorageUserVoteDetails_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageUserVoteDetails_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageEnumerateUserSharedWorkshopFilesResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageEnumerateUserSharedWorkshopFilesResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageEnumerateUserSharedWorkshopFilesResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStorageSetUserPublishedFileActionResult_t) && Packsize.IsLargePack)
					Impl<RemoteStorageSetUserPublishedFileActionResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStorageSetUserPublishedFileActionResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoteStoragePublishedFileUpdated_t) && Packsize.IsLargePack)
					Impl<RemoteStoragePublishedFileUpdated_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoteStoragePublishedFileUpdated_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(SteamUGCDetails_t) && Packsize.IsLargePack)
					Impl<SteamUGCDetails_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<SteamUGCDetails_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(CreateItemResult_t) && Packsize.IsLargePack)
					Impl<CreateItemResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<CreateItemResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(ItemInstalled_t) && Packsize.IsLargePack)
					Impl<ItemInstalled_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<ItemInstalled_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(DownloadItemResult_t) && Packsize.IsLargePack)
					Impl<DownloadItemResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<DownloadItemResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(AddUGCDependencyResult_t) && Packsize.IsLargePack)
					Impl<AddUGCDependencyResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<AddUGCDependencyResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoveUGCDependencyResult_t) && Packsize.IsLargePack)
					Impl<RemoveUGCDependencyResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoveUGCDependencyResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(AddAppDependencyResult_t) && Packsize.IsLargePack)
					Impl<AddAppDependencyResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<AddAppDependencyResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(RemoveAppDependencyResult_t) && Packsize.IsLargePack)
					Impl<RemoveAppDependencyResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<RemoveAppDependencyResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(GetAppDependenciesResult_t) && Packsize.IsLargePack)
					Impl<GetAppDependenciesResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<GetAppDependenciesResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(DeleteItemResult_t) && Packsize.IsLargePack)
					Impl<DeleteItemResult_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<DeleteItemResult_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(ValidateAuthTicketResponse_t) && Packsize.IsLargePack)
					Impl<ValidateAuthTicketResponse_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<ValidateAuthTicketResponse_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(MicroTxnAuthorizationResponse_t) && Packsize.IsLargePack)
					Impl<MicroTxnAuthorizationResponse_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<MicroTxnAuthorizationResponse_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(LeaderboardEntry_t) && Packsize.IsLargePack)
					Impl<LeaderboardEntry_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<LeaderboardEntry_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(LeaderboardScoreUploaded_t) && Packsize.IsLargePack)
					Impl<LeaderboardScoreUploaded_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<LeaderboardScoreUploaded_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(LeaderboardUGCSet_t) && Packsize.IsLargePack)
					Impl<LeaderboardUGCSet_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<LeaderboardUGCSet_t_LargePack>(unmanaged);
				
				if (typeof(T) == typeof(SteamNetConnectionInfo_t) && Packsize.IsLargePack)
					Impl<SteamNetConnectionInfo_t>.Marshaller = (unmanaged) =>
						System.Runtime.InteropServices.Marshal.PtrToStructure<SteamNetConnectionInfo_t_LargePack>(unmanaged);
				
			}
		}
	}
}
#endif // !DISABLESTEAMWORKS
