name: Build & Publish Steamworks.NET.AnyCPU
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (e.g., 2025.162.1)'
        required: true
        type: string
      publish:
        description: 'Publish to nuget.org?'
        required: false
        type: boolean

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout code

jobs:
  build:
    name: Pack and create artifact
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Pack Steamworks.NET.AnyCPU
        run: |
          dotnet pack ./Standalone3.0/Steamworks.NET.csproj \
            --configuration Release \
            -p:Version=${{ github.event.inputs.version }}

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./Standalone3.0/bin/Release/*.nupkg
          retention-days: 30

  publish:
    name: Publish to nuget.org
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.publish == 'true' }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./packages

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: vars.NUGET_USER # Set this variable in workflows > vars
      
      - name: NuGet push
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json